# Generated by Django 2.2.5 on 2020-02-05 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(max_length=300)),
                ('date_sent', models.DateField()),
                ('approval_status', models.IntegerField()),
                ('other', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.OtherUserInfo')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.StudentUserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='LabRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(max_length=300)),
                ('date_sent', models.DateField()),
                ('approval_status', models.IntegerField()),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.LabUserInfo')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.StudentUserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='BTPRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(max_length=300)),
                ('date_sent', models.DateField()),
                ('approval_status', models.IntegerField()),
                ('btp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.BTPUserInfo')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.StudentUserInfo')),
            ],
        ),
    ]
