# Generated by Django 2.2.5 on 2020-02-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_btprequest_labrequests_otherrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuserinfo',
            name='rollnumber',
            field=models.IntegerField(),
        ),
    ]
