# Generated by Django 3.0a1 on 2020-02-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200205_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btprequest',
            name='remark',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=264, unique=True),
        ),
        migrations.AlterField(
            model_name='labrequests',
            name='remark',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='otherrequest',
            name='remark',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='studentuserinfo',
            name='rollnumber',
            field=models.IntegerField(unique=True),
        ),
    ]
