# Generated by Django 2.2.5 on 2020-02-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20200214_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoduserinfo',
            name='isBTP',
            field=models.BooleanField(default=False),
        ),
    ]
