# Generated by Django 2.2.5 on 2020-02-15 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_hoduserinfo_isbtp'),
    ]

    operations = [
        migrations.AddField(
            model_name='btprequest',
            name='hod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.HODUserInfo'),
        ),
    ]
