# Generated by Django 2.2.5 on 2020-02-15 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_btprequest_hod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btprequest',
            name='btp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.BTPUserInfo'),
        ),
    ]
