# Generated by Django 3.0a1 on 2020-03-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20200215_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labuserinfo',
            name='department',
        ),
        migrations.AddField(
            model_name='labuserinfo',
            name='department',
            field=models.ManyToManyField(to='main_app.Department'),
        ),
    ]
